language: python
python:
  - "3.6"

services:
  - postgresql
  
install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database yummydb_test;' -U postgres
  
script:
  - nosetests
  - nosetests --with-coverage --cover-package=app
  - coveralls

after_sucess:
  - "coveralls"
