"""empty message

Revision ID: 1bf338d818f4
Revises: 18d62291bdda
Create Date: 2018-01-16 12:13:33.941087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf338d818f4'
down_revision = '18d62291bdda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('recipe_name', sa.String(length=100), nullable=False))
    op.drop_column('recipes', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('recipes', 'recipe_name')
    # ### end Alembic commands ###
