"""empty message

Revision ID: 84c47735a739
Revises: 1f24ed0ce18e
Create Date: 2017-12-12 23:34:25.986979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c47735a739'
down_revision = '1f24ed0ce18e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipes_user_id_fkey', 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('recipes_user_id_fkey', 'recipes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
