"""empty message

Revision ID: b2c2d57209db
Revises: e93ab3f7aea3
Create Date: 2018-01-17 08:58:47.367988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c2d57209db'
down_revision = 'e93ab3f7aea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_resets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reset_code', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='password_resets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='password_resets_pkey')
    )
    # ### end Alembic commands ###
